title: Felipe's Place
description: A resting place for Puppy.

url: http://scy1505.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: Research
   url: /research 
 - title: Posts
   url: /articles


social:
   github: scy1505
   twitter: jperezvallejo
   facebook: juan1505
   email: felipe.perez.ds@gmail.com

google_analytics: "UA-58263416-1"
